id: P009235
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:19.636434
source_metadata:
  id: bdr:W1KG4601
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ།
  author: ''
  volumes:
    31489acf5b9e4644997882fbba5bb491:
      image_group_id: I1KG4612
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
