id: IC21EC4ED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T07:58:30+00:00'
last_modified: '2022-06-08T09:34:37.924160+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4601
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E99B:
      image_group_id: I1KG4612
      title: ''
      total_pages: 324
      order: 1
      base_file: E99B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
