id: IC21EC4ED
legacy_id: P009235
ocr_import_info:
  bdrc_scan_id: W1KG4601
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T07:56:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:46:00.006649+00:00'
last_modified: 2022-09-01 00:46:10.251297
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4601
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4601
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ།
  author: སྡེ་པ་དགེ་བཤེས་ངག་དབང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9701752888189275
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG4612:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4612
      total_pages: 324
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4612.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9701752888189275
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
